const products=[
    {
        _id:"1",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"2",
        name:"苹果12  64G",
        image:"/images/iphone-12.jpg",
        description:"iphone12  采用一块6.8英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:2,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"3",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"4",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"5",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"6",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"7",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },
    {
        _id:"8",
        name:"苹果12 mini 64G",
        image:"/images/iphone-12mini.jpg",
        description:"iphone12 mini 采用一块5.4英寸1080P分辨率的屏幕,支持4K 60fps录制,IP68防水,搭载苹果A14仿生芯片",
        brand:"苹果",
        category:"电子产品",
        price:5499,
        countInStock:7,
        rate:4.0,
        numReviews:5,
    },

]
export default products